server:
  port: 18001
spring:
  application:
    name: taskhandle
  servlet:
    #上传文件大小限制  开大一点
    multipart:
      max-file-size: 99999999
      max-request-size: 99999999
  cloud:
    nacos:
      discovery:
        server-addr: 10.131.18.162:8848
  kafka:

    bootstrap-servers: 10.131.18.162:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      #生产者每个批次最多放多少条记录
      batch-size: 16384
      #https://blog.csdn.net/u010711495/article/details/113250402
      #生产者一端总的可用发送缓冲区大小，此处可设置为32M
      properties:
        max:
          request:
            size: 2147483647
        request:
          timeout:
            ms: 30000000
      buffer-memory: 2147483647 #生产者缓冲区大小

    #      properties: max.request.size = 5242880
    #      buffer-memory: 1GB
    listener:
      ack-count: 1

taskKafkaTopic: topic-task-queue

data:
  save: /Users/dailinfeng/Desktop/dataops/result
  dataPath: /Users/dailinfeng/Desktop/dataops/data
  serverBaseUrl: http://10.131.18.162:8000/task
#  serverBaseUrl: http://127.0.0.1:8000/task

forest:
  variables:
#    baseUrl: http://10.131.18.62:8000
    baseUrl: http://127.0.0.1:8000
    notifyUrl: http://10.131.18.162:5700   #qq 机器人的url