server:
  port: 18005
spring:
  application:
    name: file_manage
  cloud:
    nacos:
      discovery:
        #        server-addr: 127.0.0.1:8848
        #        server-addr: 10.23.71.70:8848
        server-addr: 10.23.71.70:8848
fileSystem:
  filePath: /Users/dailinfeng/Desktop/实验室项目/sec


forest:
  variables:
    baseUrl: http://10.23.71.70:8000 #文件下载和远程调用的url
    #    baseUrl: http://127.0.0.1:8000
    notifyUrl: http://10.23.71.70:5700   #qq 机器人的url