server:
  port: 18006
path:
  home: D:/user/
spring:
  application:
    name: usermanage
  cloud:
    nacos:
      discovery:
        #        server-addr: 127.0.0.1:8848
        #        server-addr: 10.23.71.70:8848
        server-addr: 10.131.18.162:8848
